# Gradle Performance & JVM Options
org.gradle.jvmargs=-Xmx2G -XX:+UseG1GC -XX:+ParallelRefProcEnabled
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.configuration-cache=false

# Mod Base Properties
mod_version=0.1.0
maven_group=com.ave
archives_base_name=AVE-addon

# Dependency Versions (Minecraft 1.21.11)
minecraft_version=1.21.11
fabric_loader_version=0.18.2
meteor_version=1.21.11-SNAPSHOT

loom.mixin.useLegacyMixinAp=false
